apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: databricks-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: REPLACE_ME_SECRET_STORE
    kind: SecretStore
  target:
    name: databricks-credentials
    creationPolicy: Owner
  data:
    - secretKey: DATABRICKS_HOST
      remoteRef:
        key: REPLACE_ME/databricks
        property: host
    - secretKey: DATABRICKS_TOKEN
      remoteRef:
        key: REPLACE_ME/databricks
        property: token
