apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jdbc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: REPLACE_ME_SECRET_STORE
    kind: SecretStore
  target:
    name: jdbc-credentials
    creationPolicy: Owner
  data:
    - secretKey: JDBC_PASSWORD
      remoteRef:
        key: REPLACE_ME/jdbc
        property: password
