apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - s3-credentials-external-secret.yaml
  - databricks-credentials-external-secret.yaml
  - snowflake-credentials-external-secret.yaml
  - jdbc-credentials-external-secret.yaml
  - local-dev-secretstore.yaml
patches:
  - target:
      kind: ExternalSecret
    patch: |-
      - op: replace
        path: /spec/secretStoreRef/name
        value: local-dev-store
  - target:
      kind: ExternalSecret
      name: s3-credentials
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: local-dummy-creds
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: local-dummy-creds
      - op: replace
        path: /spec/data/1/remoteRef/property
        value: secret_access_key
  - target:
      kind: ExternalSecret
      name: jdbc-credentials
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: local-dummy-creds
      - op: replace
        path: /spec/data/0/remoteRef/property
        value: jdbc_password
  - target:
      kind: ExternalSecret
      name: snowflake-credentials
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: local-dummy-creds
      - op: replace
        path: /spec/data/0/remoteRef/property
        value: snowflake_password
  - target:
      kind: ExternalSecret
      name: databricks-credentials
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: local-dummy-creds
      - op: replace
        path: /spec/data/0/remoteRef/property
        value: databricks_host
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: local-dummy-creds
      - op: replace
        path: /spec/data/1/remoteRef/property
        value: databricks_token
