apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snowflake-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: REPLACE_ME_SECRET_STORE
    kind: SecretStore
  target:
    name: snowflake-credentials
    creationPolicy: Owner
  data:
    - secretKey: SNOWFLAKE_PASSWORD
      remoteRef:
        key: REPLACE_ME/snowflake
        property: password
